# Generated by Django 4.0.6 on 2022-07-09 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0002_alter_actor_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда рейтинга',
                     'verbose_name_plural': 'Звезды рейтинга'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars',
                                    to='movies.movie', verbose_name='фильм'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews',
                                    to='movies.movie', verbose_name='фильм'),
        ),
    ]
