# Generated by Django 4.0.6 on 2022-07-10 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0003_alter_ratingstar_options_alter_rating_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie',
                                    verbose_name='фильм'),
        ),
    ]
